Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -41,3 +41,11 @@ jobs:
         python -m pip install --upgrade pip
         #pip install flask numpy --index-url $PIP_INDEX_URL
         if [ -f requirements.txt ]; then pip install -r requirements.txt --index-url $PIP_INDEX_URL; fi
+
+    - name: Snyk test
+      env:
+        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      run: |
+        npm -g i snyk
+        snyk auth "${SNYK_TOKEN}"
+        snyk test --file=requirements.txt || true  # don't fail the build; adjust to your policy
